export const BLACK = '#000000';
export const BLACK_OPACITY = BLACK + '50';
export const WHITE = '#ffffff';
export const RED = '#ff3738';
export const GRAY = '#333';
export const BLUE = 'steelblue';
export const ACCENT = '#2cbdc7';
export const ICON_COLOR = '#a0a1a3'
export const TRANSPARENT = 'transparent';
